check buildroot as other scripts

diff --git a/gprintify b/gprintify
--- a/gprintify
+++ b/gprintify
@@ -1,6 +1,15 @@
 #!/bin/sh
-
 # $Id$
+
+if [ -z "$RPM_BUILD_ROOT" ]; then
+    echo "No build root defined" >&2
+    exit 1
+fi
+
+if [ ! -d "$RPM_BUILD_ROOT" ]; then
+    echo "Invalid build root" >&2
+    exit 1
+fi
 
 if test -z "$DONT_GPRINTIFY"; then
     scripts=
diff --git a/remove_info_dir b/remove_info_dir
--- a/remove_info_dir
+++ b/remove_info_dir
@@ -1,8 +1,16 @@
 #!/bin/sh
 
-INFODIR=`rpm --eval %{_infodir}/dir`
+if [ -z "$RPM_BUILD_ROOT" ]; then
+    echo "No build root defined" >&2
+    exit 1
+fi
 
-test -n "$RPM_BUILD_ROOT" || exit 0
+if [ ! -d "$RPM_BUILD_ROOT" ]; then
+    echo "Invalid build root" >&2
+    exit 1
+fi
+
+INFODIR=`rpm --eval %{_infodir}/dir`
 
 dir="$RPM_BUILD_ROOT/$INFODIR"
 
